apiVersion: batch/v1
kind: Job
metadata:
  name: create-user
spec:
  backoffLimit: 4
  template:
    metadata:
      name: create-user
    spec:
      nodeSelector:
        type: tooling
      containers:
        - name: create-user
          image: smartbox/brain
          command: ["rails", "runner"]
          args: ["User.create(username: 'test', email: 'test@example.com', password: 'test')"]
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: brain-config
                  key: rails.env
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brain-secrets
                  key: mysql_root_password
      restartPolicy: Never
