apiVersion: batch/v1
kind: Job
metadata:
  name: uploader
spec:
  backoffLimit: 4
  template:
    metadata:
      name: uploader
    spec:
      nodeSelector:
        type: tooling
      containers:
      - name: uploader
        image: smartbox/uploader
        command: ["ls"]
      restartPolicy: Never
